### ISSUE TITLE
Twitch issues

### ISSUE THREAD

**Issue by j-r-t** [itteco/iframely#302]
I am having some issues with Twitch on my self-hosted ( been using iframey for a while in a dev environment)

So around 5 out of 6 calls twitch will return the wrong meta - you will get a white twitch logo eg https://static-cdn.jtvnw.net/ttv-static-metadata/twitch_logo3.jpg

One of out 6 times (or thereabouts) you'll get the proper embed

I have tried to debug it but its quite a big library tbf and it will probably take me days and I don't know if its a bug or not

Any help would be really appreciated

**Comment by iparamonau** [comment]
The fix is in `develop` branch for an issue that prevented a fallback to prerendering service for Twitch. You also need to add twitch parent to the config option to make their players work.

**Comment by j-r-t** [comment]
@iparamonau do I need to use a prerenderer for twitch ? maybe that's the issue?

**Comment by iparamonau** [comment]
You can hardcode it in the `proxy` to always use prerender for Twitch as well, yes. The patch made the patch for auto-detection of that fallback, so it should now work either way.

**Comment by j-r-t** [comment]
sorry I still don't understand why sometimes it works and sometimes it doesn't though (without any renderer) eg:

![image](https://user-images.githubusercontent.com/2971832/99445522-8e193200-2915-11eb-9481-3e54a78f64ab.png)

**Comment by j-r-t** [comment]
`{"type":"link","version":"1.0","title":"TheRealzBlueWater - Twitch","url":"https://www.twitch.tv/therealzbluewater","provider_name":"Twitch","description":"The #1 Stream to Have Fun, Relax, Engage and Enjoy! . Everyone in this Stream is a friend, so say hi!","thumbnail_url":"https://static-cdn.jtvnw.net/ttv-static-metadata/twitch_logo3.jpg","messages":["Twitch requires each domain your site uses. Please configure in your providers settings or add to URL itself as &parent=...","Twitch requires each domain your site uses. Please configure in your providers settings or add to URL itself as &parent=...","Twitch requires each domain your site uses. Please configure in your providers settings or add to URL itself as &parent=...","Twitch requires each domain your site uses. Please configure in your providers settings or add to URL itself as &parent=..."]}`

vs

`{"type":"video","version":"1.0","title":"TheRealzBlueWater - Twitch","url":"https://www.twitch.tv/therealzbluewater","provider_name":"Twitch","description":"The #1 Stream to Have Fun, Relax, Engage and Enjoy! . Everyone in this Stream is a friend, so say hi!","thumbnail_url":"https://static-cdn.jtvnw.net/jtv_user_pictures/therealzbluewater-profile_image-0a824779e2ea350d-300x300.jpeg","html":"<div><div style=\"left: 0; width: 100%; height: 0; position: relative; padding-bottom: 56.25%;\"><iframe src=\"https://player.twitch.tv/?channel=therealzbluewater&amp;autoplay=false&amp;parent=localhost\" style=\"border: 0; top: 0; left: 0; width: 100%; height: 100%; position: absolute;\" allowfullscreen scrolling=\"no\" allow=\"encrypted-media\"></iframe></div></div>","messages":["Twitch requires each domain your site uses. Please configure in your providers settings or add to URL itself as &parent=...","Twitch requires each domain your site uses. Please configure in your providers settings or add to URL itself as &parent=..."]}`
