### ISSUE TITLE
Youtube Playlists are not working

### ISSUE THREAD

**Issue by manikmi** [itteco/iframely#70]
Hi,

I am trying to embed the Youtube playlists. I tried the following url:
https://www.youtube.com/playlist?list=PLUKIYfIwJBdRlTd4rvMwYGaCRBDm8u1MQ
It is not returning any data. Can you help?

Regards,
Manik Mittal

**Comment by manikmi** [comment]
I am able to run it on my local server. But if I deploy it on my AWS server, it is not working. Do you see what can be the issue? I have got the APIKey from here (sceen capture below):

![image](https://cloud.githubusercontent.com/assets/797398/7982715/193b03c6-0ad7-11e5-90ac-d681c0bcd7e8.png)

Also, I have enabled the Youtube Data API v3

![image](https://cloud.githubusercontent.com/assets/797398/7982759/559b8480-0ad7-11e5-8918-6fa92f28fc63.png)

**Comment by iparamonau** [comment]
YouTube playlists work with oEmbed rather then Data API, so that shouldn't be the issue. 

YouTube removed auto-discovery for their oEmbed for playlists. We fixed that now, but this would only add meta and thumbnail. The player itself should be returned by Iframely for you. 

[Here's the result](http://iframely.com/debug?uri=https%3A%2F%2Fwww.youtube.com%2Fplaylist%3Flist%3DPLUKIYfIwJBdRlTd4rvMwYGaCRBDm8u1MQ) for the version you are running.

**Comment by iparamonau** [comment]
Do you still have this issue? We would need further input to help you out. For example, try to curl YouTube playlist from your AWS to make sure it's not SSL/network issue.

**Comment by manikmi** [comment]
Yes, I am still facing this issue. I tried curl for this url:
https://www.youtube.com/playlist?list=PLUKIYfIwJBdRlTd4rvMwYGaCRBDm8u1MQ
It showed me the full html. But, it still is not working on Iframely. Same
for Google maps.
It returns back the following json:

{
  "type": "link",
  "version": "1.0",
  "title": "Bingo audio books",
  "favicon": "https://s.ytimg.com/yts/img/favicon_32-vfl8NGn4k.png"
}


Similarly for Google maps:


{
  "type": "link",
  "version": "1.0",
  "title": "Google Maps",
  "provider_name": "Google Maps",
  "favicon": "https://maps.gstatic.com/favicon4.ico"
}


Although, Youtube videos are working fine. Only Youtube playlists and
google maps are facing issues.


On Mon, Jun 8, 2015 at 9:36 PM, Ivan Paramonau <notifications@github.com>
wrote:

> Do you still have this issue? We would need further input to help you out.
> For example, try to curl YouTube playlist from your AWS to make sure it's
> not SSL/network issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/itteco/iframely/issues/70#issuecomment-110055083>.
>



-- 
Regards,
Manik Mittal

**Comment by iparamonau** [comment]
OK, in that case we would need a copy of your local config file to try to repeat the problem. Please send it to support@iframely.com (mention #70).

**Comment by manikmi** [comment]
Sent the email to support@iframely.com

On Tue, Jun 9, 2015 at 9:39 AM, Ivan Paramonau <notifications@github.com>
wrote:

> OK, in that case we would need a copy of your local config file to try to
> repeat the problem. Please send it to support@iframely.com (mention #70
> <https://github.com/itteco/iframely/issues/70>).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/itteco/iframely/issues/70#issuecomment-110217644>.
>



-- 
Regards,
Manik Mittal
